if-else:
	g++ -o if-else if-else.cpp 

switch:
	g++ -o switch switch.cpp 

ternary:
	g++ -o ternary ternary.cpp

for-loop:
	g++ -o for-loop for-loop.cpp

while-loop:
	g++ -o while-loop while-loop.cpp

do-while-loop:
	g++ -o do-while-loop do-while-loop.cpp

clean:
	rm *.exe if-else switch ternary for-loop while-loop do-while-loop