signed_unsigned_auto:
	g++ -o signed_unsigned_auto signed_unsigned_auto.cpp 

static_inline:
	g++ -std=c++17 -o static_inline static_inline.cpp 

volatile_register:
	g++ -S -O1 -o volatile_register volatile_register.cpp 

clean:
	rm *.exe signed_unsigned_auto static_inline volatile_register